networks:
  default:
    name: kafka-flink-network
    external: True
services:


  #########################
  # TimescaleDB (Postgres) #
  #########################
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: transit_delays
    ports:
      - "5432:5432"
    networks:
      - default

    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data

  ###########
  # Batch Service #
  ###########
  pyspark-batch:
    build:
      context: ./jobs/batch
      dockerfile: Dockerfile
    container_name: pyspark-batch
    depends_on:
      - timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: transit_delays
      POSTGRES_HOST: timescaledb
    volumes:
      - ./jobs/batch:/app
    #      - ./jobs/batch/schemas:/app/schemas
    networks:
      - default
    command: tail -f /dev/null



  ################
  # Airflow Setup
  ################

  airflow-init:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow-init
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: >
      /bin/bash -c "
        airflow db init &&
        airflow db upgrade &&
        airflow users create -r Admin -u admin -e airflow@airflow.com -f admin -l user -p airflow
      "
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/db/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    networks:
      - default
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/db:/usr/local/airflow/db

  airflow-webserver:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow-webserver
    command: webserver
    depends_on:
      - airflow-init
      - timescaledb
      - pyspark-batch
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/db/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/db:/usr/local/airflow/db
      - /var/run/docker.sock:/var/run/docker.sock


  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      - airflow-init
    restart: always
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/db/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    networks:
      - default
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/db:/usr/local/airflow/db
      - /var/run/docker.sock:/var/run/docker.sock


  ###############
  # Zookeeper #
  ###############
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - default
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "-w", "5", "localhost", "2181", "|", "grep", "imok"]
      interval: 10s
      timeout: 5s
      retries: 5


  #################
  # Kafka Broker #
  #################
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  ################
  # Kafka Producer Setup
  ################
  mbta-producer:
    build:
      context: ./jobs/streaming/producer-proto
    container_name: mbta-producer
    depends_on:
      kafka:
        condition: service_healthy
      timescaledb:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    env_file:
      - .env
    networks:
      - default
    restart: always
    command: ["python", "-u", "producer.py"]


  mbta-consumer:
    build:
      context: ./jobs/streaming/consumer
    container_name: mbta-consumer
    depends_on:
      kafka:
        condition: service_healthy
      timescaledb:
        condition: service_started
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: timescaledb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - default
    restart: always

###################
#  # Flink JobManager#
#  ##################
#  flink-jobmanager:
#    image: apache/flink:1.16-scala_2.12
#    container_name: flink-jobmanager
#    ports:
#      - "8081:8081"  # Flink Web UI
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
#    volumes:
#      - ./jobs/streaming/consumer-pyflink:/app
#    command: jobmanager
#
#  ##################
#  # Flink TaskManager#
#  ##################
#  flink-taskmanager:
#    image: apache/flink:1.16-scala_2.12
#    container_name: flink-taskmanager
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
#    depends_on:
#      - flink-jobmanager
#    command: taskmanager
#
#######################
#  # Flink Consumer Job #
#  ######################
#  consumer-flink:
#    build:
#      context: jobs/streaming/consumer-pyflink
#    container_name: consumer-flink
#    depends_on:
#      - kafka
#      - flink-jobmanager
#      - timescaledb
#    environment:
#      - FLINK_JOBMANAGER_URL=flink-jobmanager:8081
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_HOST=timescaledb
#    volumes:
#      - ./jobs/streaming/consumer-pyflink:/app
#    command: ["/bin/sh", "-c", "sleep 30 && flink run -m flink-jobmanager:6123 -py /app/consumer.py"]

#    command: ["flink", "run", "-m", "flink-jobmanager:6123", "-py", "/app/consumer.py"]


#  ########################n
#  # Streamlit Dashboard  #
#  ########################
#  streamlit:
#    build:
#      context: ./dashboard
#      dockerfile: Dockerfile-streamlit
#    container_name: streamlit
#    ports:
#      - "8501:8501"
#    environment:
#      - STREAMLIT_SERVER_PORT=8501
#      - STREAMLIT_SERVER_HEADLESS=true
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=transit_delays
#      - POSTGRES_HOST=timescaledb
#    depends_on:
#      - timescaledb
#    networks:
#      - kafka-flink-network